package com.example.utils.responces

import com.example.models.Message

val SUCCESS_LOGIN = Message("LOGGED IN SUCCESSFULLY")
val FAILURE_LOGIN = Message("INVALID CREDENTIALS")
val SUCCESS_SONGADD = Message("SONG ADDED SUCCESSFULLY")
val SUCCESS_REGISTATION = Message("USER REGISTERED IN SUCCESSFULLY")
val SUCCESS_PLAYLIST = Message("PLAYLIST CREATED SUCCESSFULLY")
val FAILURE_CREDENTIALS = Message("INCORRECT CREDENTIALS GIVEN")
val SUCCESS_DELETION = Message("PLAYLIST DELETED SUCCESSFULLY")
val SUCCESS_REMOVAL = Message("REMOVED SONG FROM PLAYLIST")
val FAILURE_SONG = Message("SONG NOT FOUND")